"""Saved native update/publication evidence; sensitivities never runtime admission."""
import json,hashlib,math
from pathlib import Path
B=Path(__file__).resolve().parent
S={'update':'out/native/ashlar_bucket_update_r176/audited-summary.json','publisher':'out/native/ashlar_queue_serial_r197/audited-summary.json','publisher_shared':'out/native/ashlar_queue_shared_history_r207/audited-summary.json'}
def calculate():
 d={k:json.loads((B/v).read_text()) for k,v in S.items()};u=d['update']['apply_metrics'];n=100000
 scenarios=[]
 for name in ['publisher','publisher_shared']:
  b=d[name]['batches'][0];service=b['processing_s'];rows=b['rows']
  for rate in [10000,100000]:
   fill=rows/rate;finish=0;queue=[]
   for i in range(12):
    ready=(i+1)*fill;start=max(ready,finish);finish=start+service
    queue.append({'batch':i+1,'wait_s':start-ready,'modeled_record_age_p95_s':finish-i*fill-.05*fill})
   scenarios.append({'source':name,'arrival_rate':rate,'observed_single_service_s':service,'fixed_service_implied_rows_per_s':rows/service,'service_to_fill_ratio':service/fill,'minimum_ideal_parallel_lanes':math.ceil(service/fill),'batches':queue})
 per={k:{'native_written_bytes_per_changed_entity':v['metrics']['write_remote_bytes']/n,'native_read_bytes_per_changed_entity':v['metrics']['read_bytes']/n,'observed_caller_s':v['caller_ms']/1000} for k,v in u.items()}
 return {'format':'ashlar-measured-capacity-sensitivity/1','source_sha256':{v:hashlib.sha256((B/v).read_bytes()).hexdigest() for v in S.values()},'update_sample_rows':n,'update_profiles':per,'partition_to_lc_write_ratio':per['part']['native_written_bytes_per_changed_entity']/per['lc']['native_written_bytes_per_changed_entity'],'publisher_100k_reported_bytes':d['publisher']['cost_totals'],'fixed_service_queue_scenarios':scenarios,'limits':['Not a sustained arrival/queue experiment; service held constant from single samples.','Ideal parallel lane count is arithmetic lower bound, not safe concurrent writers or resource recommendation. Shared warehouse/manifest conflicts, validation, source transactions and skew prevent linear scaling assumptions.','Update sample is a previously hot100k set with differing maintenance histories; fresh uniformly scattered updates may touch many more base files.','Reported reads exclude unreported physical I/O; billing, retained-version storage and source staging are additional.','No edge-byte width transferred to nodes and no billion-node/runtime admission.'],'next_stage':{'nodes':8000000,'edges':40000000,'status':'proposed; bounds must be enforced before admission','build':{'edge_slice_rows':1000000,'per_statement_wall_s':180,'estimated_edge_current_bytes_range':[60000000000,100000000000],'total_new_committed_bytes_stop':140000000000,'reported_read_bytes_stop':400000000000,'cumulative_wall_s_stop':3600},'requirements':['Re-inventory existing compute, free local disk and metering; do not resize/provision.','Full0.3 schema, distinct variable payload/property/retained corpus, typed endpoint and identity checks; include all source/history/manifest roles and account their bytes separately.','Before each chunk reserve remaining build+validation+update bytes; stop if observed projected total exceeds cap. Caps include failed native work where reported.','Validate every generated row through bounded range-wise exact oracle comparisons, unique IDs and typed endpoint joins; do not use samples as full preservation proof.','Fresh scattered updates and repeated hot-key updates are separate workload cells; include raw/current/journal exact barrier and source-arrival clocks.','Measure singleton/concurrent reads with cache/remote and all compiler/caller phases; controlled cold requires independently justified cache-state protocol.','Use persisted handles and terminal native histories; no unknown-write retries. Retain evidence and temporary data; no VACUUM.','Do not admit1B/5B from this stage or omit unresolved billing/retention costs.']}}
if __name__=='__main__':
 r=calculate();(B/'out/measured-capacity-r213.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'update_profiles':r['update_profiles'],'write_ratio':r['partition_to_lc_write_ratio'],'queue_summary':[{k:v for k,v in x.items() if k!='batches'} for x in r['fixed_service_queue_scenarios']]},indent=2))
