"""Independent complete common-file native receipt audit, no query execution."""
import json,hashlib
from pathlib import Path
from mixed_change_queries_r230 import row_hash_sql
from overlay_sql_r395 import FIELDS
B=Path(__file__).resolve().parent;p=B/'out/native/ashlar_common_carriers_pilot_r621';a=json.loads((p/'summary.json').read_text());assert a['state']=='All20 pilot common-file complete carrier multisets and live typed identities preserved at E10/E12';source=B/'out/native/ashlar_sparse_maintain_r610/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());assert a['table']==s['table'] and a['versions']==[10,12];inv=json.loads((B/'out/native/ashlar_current_file_ranges_r606/summary.json').read_text());old={r[0]:r for r in inv['files']};new={r[0]:r for r in s['after_files']};all_common=set(old)&set(new);assert len(all_common)==600;common=set(sorted(all_common)[:20]);assert len(common)==20 and a['common_files']==sorted(common) and all(old[k]==new[k] for k in common);rs=list(map(json.loads,(p/'statements.jsonl').read_text().splitlines()));h=json.loads((p/'shared-history.json').read_text());qs={q['query_id']:q for q in h['queries']};assert len(rs)==len(qs)==len({r['statement_id'] for r in rs})==5 and h['require_final'] and not h['missing_ids'];by={r['label']:r for r in rs}
for r in rs:
 q=qs[r['statement_id']];assert q['status']=='FINISHED' and q['is_final'] and q['query_text']==r['sql'] and r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
for version,exclude in [(10,s['removed_files']),(12,s['added_files'])]:
 literals=','.join("decode(unhex('"+r[0].encode().hex()+"'),'UTF-8')" for r in [old[k] for k in sorted(common)])
 query=f"SELECT _metadata.file_path,count(*),count(DISTINCT struct(source_system,rel_type_id,id)),sha2(concat_ws('',sort_array(collect_list({row_hash_sql(FIELDS)}))),256) FROM {a['table']['table']} VERSION AS OF {version} WHERE _metadata.file_path IN ({literals}) GROUP BY _metadata.file_path ORDER BY _metadata.file_path"
 r=by['common-'+str(version)];assert r['sql']==query and not qs[r['statement_id']]['metrics'].get('result_from_cache');rows=r['response']['result']['data_array'];assert rows==a['checks'][str(version)] and len(rows)==20 and {x[0]:int(x[1]) for x in rows}=={k:int(old[k][2]) for k in common};assert all(x[1]==x[2] and len(x[3])==64 for x in rows)
assert a['checks']['10']==a['checks']['12'];assert sum(int(r[1]) for r in a['checks']['10'])==a['expected_rows'];cols=[x['name'] for x in by['detail']['response']['manifest']['schema']['columns']];assert dict(zip(cols,by['detail']['response']['result']['data_array'][0]))['id']==a['table']['id']
for label in ['head','final-head']:assert by[label]['response']['result']['data_array'][0][0]=='12'
costs={k:sum(q['metrics'].get(k,0) for q in qs.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<180;a['audit']={'native_final_statements':5,'common_files':20,'complete_common_live_rows':a['expected_rows'],'whole_graph_preservation_proved':False,'qualification':a['qualification'],'source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','shared-history.json']}};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['audit'])
