"""Independent exhaustive paired common-file audit, exact nonoverlapping coverage."""
import json,hashlib
from pathlib import Path
from mixed_change_queries_r230 import row_hash_sql
from overlay_sql_r395 import FIELDS
B=Path(__file__).resolve().parent;p=B/'out/native/ashlar_common_carriers_remaining_r624';a=json.loads((p/'summary.json').read_text());assert a['state']=='All600 common-file complete carrier multisets and live typed identities preserved at E10/E12';source=B/'out/native/ashlar_sparse_maintain_r610/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());pilot_path=B/'out/native/ashlar_common_carriers_pilot_r621/audited-summary.json';assert hashlib.sha256(pilot_path.read_bytes()).hexdigest()==a['pilot_sha256'];pilot=json.loads(pilot_path.read_text());assert pilot['audit']['common_files']==20 and not pilot['audit']['whole_graph_preservation_proved']
for folder,data,key in [('ashlar_sparse_maintain_r610',s,'receipt_sha256'),('ashlar_common_carriers_pilot_r621',pilot,'source_sha256')]:
 for n,digest in data['audit'][key].items():assert hashlib.sha256((B/'out/native'/folder/n).read_bytes()).hexdigest()==digest
assert a['table']==s['table'] and a['versions']==[10,12];inv=json.loads((B/'out/native/ashlar_current_file_ranges_r606/summary.json').read_text());old={r[0]:r for r in inv['files']};new={r[0]:r for r in s['after_files']};common=set(old)&set(new);assert len(common)==600 and a['common_files']==sorted(common) and all(old[k]==new[k] for k in common);done=set(pilot['common_files']);assert done==set(sorted(common)[:20]);remaining=sorted(common-done);groups=[remaining[i:i+20] for i in range(0,580,20)];assert len(groups)==29 and sum(map(len,groups))==len(set(k for g in groups for k in g))==580 and done.isdisjoint(remaining)
rs=list(map(json.loads,(p/'statements.jsonl').read_text().splitlines()));h=json.loads((p/'shared-history.json').read_text());qs={q['query_id']:q for q in h['queries']};assert len(rs)==len(qs)==len({r['statement_id'] for r in rs})==61 and h['require_final'] and not h['missing_ids'];by={r['label']:r for r in rs};assert len(by)==61
for r in rs:
 q=qs[r['statement_id']];assert q['status']=='FINISHED' and q['is_final'] and q['query_text']==r['sql'] and r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
accepted={v:list(pilot['checks'][v]) for v in ['10','12']};assert len(a['completed_groups'])==29
for index,paths in enumerate(groups):
 assert a['completed_groups'][index]=={'index':index,'files':paths,'rows':sum(int(old[k][2]) for k in paths)}
 for version in [10,12]:
  literals=','.join("decode(unhex('"+k.encode().hex()+"'),'UTF-8')" for k in paths)
  query=f"SELECT _metadata.file_path,count(*),count(DISTINCT struct(source_system,rel_type_id,id)),sha2(concat_ws('',sort_array(collect_list({row_hash_sql(FIELDS)}))),256) FROM {a['table']['table']} VERSION AS OF {version} WHERE _metadata.file_path IN ({literals}) GROUP BY _metadata.file_path ORDER BY _metadata.file_path"
  r=by['common-'+str(version)+'-'+str(index)];assert r['sql']==query and not qs[r['statement_id']]['metrics'].get('result_from_cache');rows=r['response']['result']['data_array'];assert len(rows)==20 and {x[0]:int(x[1]) for x in rows}=={k:int(old[k][2]) for k in paths} and all(x[1]==x[2] and len(x[3])==64 for x in rows);accepted[str(version)].extend(rows)
for v in ['10','12']:
 accepted[v].sort(key=lambda r:r[0]);assert accepted[v]==a['checks'][v] and len({r[0] for r in accepted[v]})==600
assert accepted['10']==accepted['12'];assert sum(int(r[1]) for r in accepted['10'])==a['expected_rows'];assert a['expected_rows']+sum(int(r[2]) for r in s['removed_files'])==a['expected_rows']+sum(int(r[2]) for r in s['added_files'])==39930000
for label in ['head','final-head']:assert by[label]['response']['result']['data_array'][0][0]=='12'
cols=[x['name'] for x in by['detail']['response']['manifest']['schema']['columns']];assert dict(zip(cols,by['detail']['response']['result']['data_array'][0]))['id']==a['table']['id']
costs={k:sum(q['metrics'].get(k,0) for q in qs.values()) for k in a['costs']};cancel=json.loads((B/'out/native/ashlar_common_carriers_r618/audited-cancel.json').read_text());prior=cancel['costs']['read_bytes']+pilot['costs']['read_bytes'];assert prior==a['prior_read_bytes'];assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and costs['read_bytes']+prior<=a['combined_read_bound'] and a['wall_s']<1800;a['audit']={'native_final_statements':61,'reused_pilot_statements':5,'common_files':600,'common_rows':a['expected_rows'],'all_live_edge_carriers':39930000,'combined_verification_read_bytes':costs['read_bytes']+prior,'source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','shared-history.json']},'qualification':a['qualification'],'full_live_carrier_preservation':'Complete20field SHA256 common-file multisets and exact rewritten-file bidirectional EXCEPTALL cover both whole live snapshots, including Delta live deletion-vector filtering. No independent raw Delta-log action proof.'};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['audit'])
