"""Audit native file intervals and model conditional hash overlap/scale."""
import json,hashlib,bisect,statistics
from pathlib import Path
from seventh_changes_r589 import SeventhChanges
B=Path(__file__).resolve().parent;d=B/'out/native/ashlar_current_file_ranges_r606';s=json.loads((d/'summary.json').read_text());r=json.loads((d/'statements.jsonl').read_text().splitlines()[0]);q=json.loads((d/'shared-history.json').read_text())['queries'][0];assert q['query_id']==r['statement_id'] and q['query_text']==r['sql'] and q['is_final'] and q['status']=='FINISHED';assert r['response']['result']['data_array']==s['files'];assert r['response']['status']['state']=='SUCCEEDED' and not r['response']['manifest'].get('truncated') and s['state']=='Pinned E10 live rows and exact physical file hash intervals measured';assert sum(int(x[2]) for x in s['files'])==39930000 and len({x[0] for x in s['files']})==len(s['files']);assert s['costs']=={k:q['metrics'].get(k,0) for k in s['costs']} and all(v<=s['bounds'][k] for k,v in s['costs'].items());w=SeventhChanges();keys=sorted(w.change(i)['before']['lookup_hash'] for i in range(100000));files=s['files'];spans=[(int(r[4],16)-int(r[3],16))/2**256 for r in files];coverage=[]
for h in keys[::1000]:coverage.append(sum(r[3]<=h<=r[4] for r in files))
covered=[r for r in files if bisect.bisect_right(keys,r[4])>bisect.bisect_left(keys,r[3])];size=sum(int(r[1]) for r in files);wide=[r for r,span in zip(files,spans) if span>.9]
ranges=[]
for i in range(64):
 lo=f'{i*4:02x}'+'0'*62;hi=f'{(i+1)*4:02x}'+'0'*62 if i<63 else None;selected=[r for r in files if r[4]>=lo and (hi is None or r[3]<hi)];ranges.append({'range':i,'lower':lo,'upper':hi,'overlapping_files':len(selected),'overlapping_physical_bytes':sum(int(r[1]) for r in selected)})
a={'hash_ranges_64':ranges,'state':'Native interval receipts audited; conditional overlap/edge-scale model computed','source_sha256':hashlib.sha256((d/'summary.json').read_bytes()).hexdigest(),'live_rows':39930000,'files':len(files),'physical_file_bytes':size,'wide_domain_files':len(wide),'wide_domain_file_bytes':sum(int(r[1]) for r in wide),'sum_live_hash_domain_spans':sum(spans),'sampled_point_interval_coverage':{'samples':len(coverage),'min':min(coverage),'median':statistics.median(coverage),'max':max(coverage)},'seventh100k_touched_intervals':len(covered),'seventh100k_touched_physical_bytes':sum(int(r[1]) for r in covered),'conditional_5B_edge_projection':{'files':len(files)*5000000000/39930000,'physical_current_file_bytes':size*5000000000/39930000},'qualification':'Exact E10 live intervals/physical file sizes, not persisted Delta statistics or exact query-pruning proof. Deleted-row statistics may be wider. Point100sample coarse and biased to existing changed identities, not service distribution. Linear5Bedge model assumes identical row mix/entropy/file geometry and excludes nodes/journal/raw/retention/log/adjacency/maintenance/concurrency; actual billion-scale untested.'};(B/'out/file-overlap-model-r607.json').write_text(json.dumps(a,indent=2)+'\n');print(json.dumps(a,indent=2))
