"""Independent native-final full-vector reference and stale-owner rollback audit."""
import hashlib,json
from pathlib import Path
B=Path(__file__).resolve().parent

def main():
 p=B/'out/native/ashlar_full_vector_authority_r369';a=json.loads((p/'summary.json').read_text());assert a['state']=='Full-vector reference append and stale-owner whole-MERGE refusal pass';rs=[json.loads(x) for x in (p/'statements.jsonl').read_text().splitlines()];native={q['query_id']:q for q in json.loads((p/'query-history.json').read_text())};assert len(rs)==len(native)==len({r['statement_id'] for r in rs});by={r['label']:r for r in rs}
 for r in rs:
  q=native[r['statement_id']];failed=r['label']=='stale-a';assert q['is_final'] and q['status']==('FAILED' if failed else 'FINISHED') and q['query_text']=='/* ashlar '+p.name+' '+r['label']+' */ '+r['sql'] and r['response']['status']['state']==('FAILED' if failed else 'SUCCEEDED')
 source=B/'out/native/ashlar_incremental_publish_r332/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());assert a['role_pins']==s['tables'];old=list(map(json.loads,(source.parent/'statements.jsonl').read_text().splitlines()));expected=next(r for r in old if r['label']=='descriptor-readback')['response']['result']['data_array'][0];assert a['original_descriptor'][:6]==expected
 for role,t in a['role_pins'].items():
  r=by['detail-'+role];cols=[x['name'] for x in r['response']['manifest']['schema']['columns']];assert dict(zip(cols,r['response']['result']['data_array'][0]))['id']==t['id'];assert by['available-'+role]['response']['result']['data_array']==[['1']] and f"VERSION AS OF {t['version']} LIMIT 1" in by['available-'+role]['sql']
 assert a['before_stale_rows']==a['after_stale_rows']==by['before-stale-rows']['response']['result']['data_array']==by['after-stale-rows']['response']['result']['data_array'];assert a['stale_statement_id']==by['stale-a']['statement_id'] and 'ASHLAR_AUTHORITY_STALE' in by['stale-a']['response']['status']['error']['message'];assert not any(r[0]=='r369-stale' for r in a['final_rows']) and a['final_rows'][0][:4]==['authority','authority','writer-b','3'] and len(a['final_rows'])==3
 for key in ['accepted_a','accepted_b']:
  accepted=a[key];r=by[accepted['label']];assert accepted['parameters']==r['parameters'] and accepted['statement_id']==r['statement_id'];text=json.dumps(accepted['descriptor'],sort_keys=True,separators=(',',':'));assert text==r['parameters']['text'] and hashlib.sha256(text.encode()).hexdigest()==r['parameters']['digest'];d=json.loads(text);assert d['role_pins']==s['tables'];assert list(d['source_descriptor'].values())!=[];assert d['source_descriptor']['table_versions_json']==expected[2] and d['source_descriptor']['source_progress_json']==expected[3] and d['source_descriptor']['schema_revisions_json']==expected[4] and d['source_descriptor']['validation_report_json']==expected[5];assert any(row[0]==d['id'] and row[4:]==[text,r['parameters']['digest']] for row in a['final_rows'])
 owned={by[n]['statement_id'] for n in ['create','seed','publish-a','transfer','publish-b']};head=int(a['final_history'][0]['version']);assert [int(c['version']) for c in a['final_history']]==list(range(head,-1,-1)) and all(c['queryHistoryStatementId'] in owned for c in a['final_history']);assert int(a['stale_history'][0]['version'])==3 and head==4
 costs={k:sum(q['metrics'].get(k,0) for q in native.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<a['bounds']['wall_s']
 a['audit']={'successful_native_final':len(rs)-1,'failed_native_final':1,'role_pins':6,'source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','query-history.json']},'qualification':a['qualification']};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['audit'])
if __name__=='__main__':main()
