"""All-six-role measured active-footprint capacity sensitivity, not admission."""
import json,hashlib,math
from pathlib import Path
B=Path(__file__).resolve().parent
source=B/'out/native/ashlar_seventh_guard_publish_r596/audited-summary.json';s=json.loads(source.read_text());assert s['state']=='Integrated private seventh100k guarded publication passes full change custody';counts={'object_current':8000000,'edge_current':39930000,'source_record':48700000,'property_journal':193516667,'adjacency_forward':39930000,'tombstone':70000};assert set(s['active_details'])==set(counts)
roles={}
for role,rows in counts.items():
 d=s['active_details'][role];assert d['id']==s['tables'][role]['id'] and d['format']=='delta';factor=1000000000/8000000 if role=='object_current' else 5000000000/39930000
 roles[role]={'observed_rows':rows,'observed_active_files':int(d['numFiles']),'observed_active_bytes':int(d['sizeInBytes']),'selected_pin':s['tables'][role],'conditional_factor':factor,'conditional_rows':rows*factor,'conditional_active_bytes':int(d['sizeInBytes'])*factor,'conditional_active_files':int(d['numFiles'])*factor}
result={'state':'Complete six-role active footprint modeled at owner1B-node/5B-edge target','source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'roles':roles,'observed_active_total_bytes':sum(r['observed_active_bytes'] for r in roles.values()),'conditional_active_total_bytes':sum(r['conditional_active_bytes'] for r in roles.values()),'next_double_graph_sensitivity':{'node_rows':16000000,'live_edge_rows':79860000,'active_role_bytes':2*sum(r['observed_active_bytes'] for r in roles.values())},'not_counted':['retained Delta versions and deletion-vector/log inventory','all prior canceled-attempt/orphan storage','local/upload/staged input duplicates','reverse adjacency/type-serving/export tables','production control/source-index/fence/manifest/receipt growth','real source retention/event fanout/skew/payload entropy','maintenance peak/coexistent rewritten files'], 'qualification':'Arithmetic only, no native growth or capacity/throughput claim. Profiles are actual post-seventh active heads (node physical8/selected6), not guaranteed size of each retained selected pin. EdgeE10 precedes separately evidenced physicalE12 maintenance. Graph mix/history-to-live ratio is frozen from seven synthetic100k batches; nodes scale125x and edge-associated roles scale5B/39.93M, not a real producer history profile. File counts scale continuously as sensitivity, not realizable count or scheduler admission. Complete storage/cost is larger/unknown; no dollar estimate/account pricing or bill supplied. No latency-gate failure reopens UCDelta.'};(B/'out/full-role-capacity-r634.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:result[k] for k in ['observed_active_total_bytes','conditional_active_total_bytes','next_double_graph_sensitivity']},indent=2))
