"""Owned legacy/write-time CDF comparison; no graph descriptor or source ACK."""
import json,time,hashlib
from pathlib import Path
from normalized_apply_sql_r276 import pin,current_merge,adjacency_merge,predecessor_check
from mixed_change_queries_r230 import row_hash_sql
from persistent_sql import Client
from publication_history import collect_history,HistoryPending
B=Path(__file__).resolve().parent

def main():
 paths={'base':'out/native/ashlar_scale_edges_r274/audited-summary.json','inputs':'out/native/ashlar_second_delta_stage_r324/audited-summary.json','oracle':'out/second-cdf-image-oracle-r327.json','predecessor':'out/native/ashlar_second_predecessor_r325/audited-summary.json','first_inputs':'out/native/ashlar_normalized_delta_stage_r275/audited-summary.json','first_oracle':'out/cdf-image-oracle-r288.json'};s={k:json.loads((B/p).read_text()) for k,p in paths.items()};raw=s['inputs']['tables']['source_record'];current=s['inputs']['tables']['current_replacement'];O=B/'out/native/ashlar_lc_second_apply_r337';assert not O.exists();O.mkdir();start=time.monotonic();c=Client(O,observation_timeout=200,cancel_after=180);a={'state':'Preparing private write-time CDF tables','source_sha256':{k:hashlib.sha256((B/p).read_bytes()).hexdigest() for k,p in paths.items()},'bounds':{'read_bytes':150000000000,'write_remote_bytes':10000000000,'spill_to_disk_bytes':5000000000,'wall_s':900,'statement_s':180},'tables':{},'checks':{},'commits':[]}
 def save():(O/'summary.json').write_text(json.dumps(a,indent=2)+'\n')
 def detail(table,label):
  r=c.sql('detail-'+label,'DESCRIBE DETAIL '+table);names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];return dict(zip(names,r[0]))
 def bind(table,sid,label):
  r=c.sql('history-'+label,'DESCRIBE HISTORY '+table+' LIMIT 20');names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];found=[dict(zip(names,x)) for x in r if dict(zip(names,x)).get('queryHistoryStatementId')==sid];assert len(found)==1;a['commits'].append({'label':label,'statement_id':sid,'history':found[0]});save();return int(found[0]['version'])
 def metrics():
  for i in range(20):
   try:h=collect_history(c.w,c.records,O/'shared-history.json');break
   except HistoryPending:
    if i==19:raise
    time.sleep(2)
  a['costs']={k:sum(x['metrics'].get(k,0) for x in h.values()) for k in ['read_bytes','write_remote_bytes','spill_to_disk_bytes']};assert all(v<=a['bounds'][k] for k,v in a['costs'].items());assert time.monotonic()-start<900;save();return h
 save()
 try:
  assert s['predecessor']['state']=='Full100k predecessor and prepared mutation-source checks pass'
  for role in ['source_record','current_replacement']:
   t=s['inputs']['tables'][role];assert detail(t['table'],'input-'+role)['id']==t['id']
  for role in ['edge_current']:
   parent=s['base']['tables']['edge_current'];assert detail(parent['table'],'parent-'+role)['id']==parent['id'];table='client_dev.ashlar_entropy_20261006_r86.lc_second_'+role+'_r337';c.sql('clone-'+role,f"CREATE TABLE {table} SHALLOW CLONE {pin(parent['table'],parent['version'])}");sid=c.records[-1]['statement_id'];clone_version=bind(table,sid,'clone-'+role);d=detail(table,role);a['tables'][role]={'table':table,'id':d['id'],'base':parent,'clone_version':clone_version};save();c.sql('disable-'+role,'ALTER TABLE '+table+' DISABLE PREDICTIVE OPTIMIZATION');settings=c.sql('maintenance-'+role,'DESCRIBE TABLE EXTENDED '+table);assert [r[1] for r in settings if r[0]=='Predictive Optimization']==['DISABLE'];c.sql('enable-cdf-'+role,"ALTER TABLE "+table+" SET TBLPROPERTIES ('delta.enableChangeDataFeed'='true','delta.targetFileSize'='67108864')");sid=c.records[-1]['statement_id'];a['tables'][role]['cdf_enable_version']=bind(table,sid,'enable-'+role);d=detail(table,'enabled-'+role);assert json.loads(d['properties'])['delta.enableChangeDataFeed']=='true';metrics()
   first=s['first_inputs']['tables'];fr=first['source_record'];fc=first['current_replacement'];q=current_merge(table,fr['table'],fr['version'],fc['table'],fc['version']);c.sql('prepare-first-merge',q);fv=bind(table,c.records[-1]['statement_id'],'prepare-first-merge');assert fv==2;a['tables'][role]['first_version']=fv
   f=s['first_oracle']['roles'][role];want=[[k,str(x['rows']),str(fv),str(fv),x['digest']] for k,x in sorted(f['images'].items())];q=f"SELECT _change_type,count(*),min(_commit_version),max(_commit_version),sha2(concat_ws('',sort_array(collect_list({row_hash_sql(f['fields'])}))),256) FROM table_changes('{table}',{fv},{fv}) GROUP BY _change_type ORDER BY _change_type";assert c.sql('prepare-first-images',q)==want;a['checks']['first']={'groups':want};assert c.sql('prepared-count',f'SELECT count(*) FROM {pin(table,fv)}')==[['39990000']]
   assert c.sql('second-predecessors',predecessor_check(raw['table'],raw['version'],table,fv))==[['100000','0']];a['preparation_s']=time.monotonic()-start;metrics()
   q=(current_merge if role=='edge_current' else adjacency_merge)(table,raw['table'],raw['version'],current['table'],current['version']);apply_start=time.monotonic();c.sql('merge-'+role,q);sid=c.records[-1]['statement_id'];a['tables'][role]['apply_caller_s']=time.monotonic()-apply_start;version=bind(table,sid,'merge-'+role);a['tables'][role]['version']=version;m=json.loads(a['commits'][-1]['history']['operationMetrics']);assert m['numTargetRowsUpdated']=='90000' and m['numTargetRowsDeleted']=='10000' and m['numTargetRowsInserted']=='0';a['state']='Checking complete legacy CDF images';save();metrics()
   expected=s['oracle']['roles'][role];q=f"SELECT _change_type,count(*),min(_commit_version),max(_commit_version),sha2(concat_ws('',sort_array(collect_list({row_hash_sql(expected['fields'])}))),256) FROM table_changes('{table}',{version},{version}) GROUP BY _change_type ORDER BY _change_type";want=[[kind,str(x['rows']),str(version),str(version),x['digest']] for kind,x in sorted(expected['images'].items())];read_start=time.monotonic();assert c.sql('all-images-'+role,q)==want;a['checks'][role]={'rows':190000,'groups':want,'cdf_read_caller_s':time.monotonic()-read_start};save();metrics()
  h=metrics();assert all(not h[r['statement_id']]['metrics'].get('result_from_cache') for r in c.records if r['label'].startswith('all-images-'));a['telemetry']={r['label']:{'caller_ms':r['wall_ms'],'metrics':h[r['statement_id']]['metrics']} for r in c.records if r['label'].startswith(('merge-','all-images-'))};a['wall_s']=time.monotonic()-start;a['state']='Liquid-clustered second-batch MERGE preserves complete190k edge images';a['qualification']='Private original40M liquid-clustered clone,64MiB target property and legacy CDF before replaying qualified first100k input. Complete first190k20-field images and full second100k predecessor equality qualify39.99M baseline. Second190k full-field images match same independent oracle as range32; exact100k inputs and identity/version predicates. Separate reconstruction/predecessor preparation costs retained. Sequential runs have different physical starting shape/cache/remote conditions; not isolated causal speedup. No whole second graph publication, maintenance, concurrent writer fence, real producer ACK, controlled cold or billion admission. No original mutation or compute resize.';save();print(json.dumps({'state':a['state'],'checks':{k:v['cdf_read_caller_s'] for k,v in a['checks'].items() if 'cdf_read_caller_s' in v},'costs':a['costs'],'wall_s':a['wall_s']},indent=2))
 except Exception as e:a.update(state='Stopped; inspect same handles and private commits; no blind replay or support claim',error=str(e));save();raise
if __name__=='__main__':main()
