"""Independent four-reader response, native overlap and exact cost audit."""
import json,hashlib,math
from pathlib import Path
from seventh_changes_r589 import SeventhChanges
from overlay_sql_r395 import FIELDS
B=Path(__file__).resolve().parent;p=B/'out/native/ashlar_maintained_concurrent_r626';a=json.loads((p/'summary.json').read_text());assert a['state']=='All64 complete maintained carriers/absence pass four synchronized readers';source=B/'out/native/ashlar_common_carriers_remaining_r624/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];proof=json.loads(source.read_text());assert proof['audit']['all_live_edge_carriers']==39930000 and a['table']=={**proof['table'],'version':12};rs=[dict(json.loads(line),worker=q.parent.name) for q in p.glob('reader-*/statements.jsonl') for line in q.read_text().splitlines()];h=json.loads((p/'shared-history.json').read_text());qs={q['query_id']:q for q in h['queries']};assert h['require_final'] and not h['missing_ids'] and len(rs)==len(qs)==len({r['statement_id'] for r in rs})==75;records={r['statement_id']:r for r in rs}
for r in rs:
 q=qs[r['statement_id']];assert q['status']=='FINISHED' and q['is_final'] and q['query_text']=='/* ashlar '+r['worker']+' '+r['label']+' */ '+r['sql'] and r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
fields=','.join('CAST(published_at AS STRING) AS published_at' if f=='published_at' else f for f in FIELDS);query=f"SELECT {fields} FROM {a['table']['table']} VERSION AS OF 12 WHERE lookup_hash=:hash AND source_system=:source AND rel_type_id=CAST(:type AS BIGINT) AND id=CAST(:id AS BIGINT)";assert query==a['query'];w=SeventhChanges();assert len(a['indices'])==len(set(a['indices']))==32 and len(a['reads'])==64 and len({(r['reader'],r['phase'],r['slot']) for r in a['reads']})==64;counts={}
for index in a['indices']:
 x=w.change(index);hash=x['before']['lookup_hash'];k=('inside' if '08'+'0'*62<=hash<'0c'+'0'*62 else 'outside',x['after'] is None);counts[k]=counts.get(k,0)+1
assert counts=={('inside',False):12,('inside',True):4,('outside',False):12,('outside',True):4}
for read in a['reads']:
 assert read['index']==a['indices'][read['slot']*4+read['reader']];x=w.change(read['index']);row=x['before'];after=x['after'];expected=[] if after is None else [[after[f].replace('T',' ').removesuffix('Z') if f=='published_at' else after[f] for f in FIELDS]];r=records[read['statement_id']];assert r['worker']=='reader-'+str(read['reader']) and r['label']=='point-'+str(read['phase'])+'-'+str(read['slot']) and r['sql']==query and r['parameters']=={'hash':row['lookup_hash'],'source':row['source_system'],'type':row['rel_type_id'],'id':row['id']} and r['response'].get('result',{}).get('data_array',[])==expected and not qs[read['statement_id']]['metrics'].get('result_from_cache')
p95=lambda xs:sorted(xs)[math.ceil(.95*len(xs))-1]
for phase in range(2):
 reads=[r for r in a['reads'] if r['phase']==phase];assert {r['index'] for r in reads}==set(a['indices']);assert a['metrics'][str(phase)]=={'caller_p95_ms':p95([records[r['statement_id']]['wall_ms'] for r in reads]),'engine_p95_ms':p95([qs[r['statement_id']]['metrics']['execution_time_ms'] for r in reads])}
overlap=[]
for phase in range(2):
 for slot in range(8):
  cohort=[r for r in a['reads'] if r['phase']==phase and r['slot']==slot];assert {r['reader'] for r in cohort}==set(range(4));native=[qs[r['statement_id']] for r in cohort];client=[records[r['statement_id']] for r in cohort];overlap.append({'phase':phase,'slot':slot,'native_request_overlap_ms':max(0,min(q['execution_end_time_ms'] for q in native)-max(q['query_start_time_ms'] for q in native)),'caller_overlap_ms':max(0,min(r['start_epoch']+r['wall_ms']/1000 for r in client)-max(r['start_epoch'] for r in client))*1000})
costs={k:sum(q['metrics'].get(k,0) for q in qs.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<300;a['audit']={'native_final_statements':75,'complete_carrier_or_absence_responses':64,'quartets':overlap,'native_overlapping_quartets':sum(x['native_request_overlap_ms']>0 for x in overlap),'qualification':a['qualification'],'overlap_note':'Native query-start to execution-end windows and caller intervals, not proof of simultaneous scans or saturation. Missing capacity metrics are unknown, not zero.','source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','shared-history.json']}};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(json.dumps({'metrics':a['metrics'],'audit':a['audit']},indent=2))
