"""First exact2M-identity append of an explicitly unfinished full39.99M comparator."""
import json,time,hashlib
from pathlib import Path
from persistent_sql import Client
from publication_history import collect_history,HistoryPending
from mixed_change_queries_r230 import row_hash_sql
B=Path(__file__).resolve().parent

def main():
 source_path=B/'out/native/ashlar_scoped_maintenance_r300/audited-summary.json';source=json.loads(source_path.read_text());budget=json.loads((B/'out/range32-comparison-budget-r308.json').read_text());failed=json.loads((B/'out/native/ashlar_range32_build_r309/cancel-audit.json').read_text());assert failed['statement_state']=='CANCELED' and not failed['target_exists'];assert hashlib.sha256(source_path.read_bytes()).hexdigest()==budget['source_sha256'];p=B/'out/native/ashlar_range32_stage_r313';assert not p.exists();p.mkdir();c=Client(p,observation_timeout=200,cancel_after=90);start=time.monotonic();target='client_dev.ashlar_entropy_20261006_r86.edge_range32_r313';parent=source['table'];fields=json.loads((B/'out/cdf-image-oracle-r288.json').read_text())['roles']['edge_current']['fields'];cols=','.join(fields);extra=budget['partition_expression'];want=source['checks']['after'][:20];expected=sum(int(r[1]) for r in want);a={'state':'Preparing first bounded range32 append','table':target,'parent':{'table':parent,'version':4,'id':source['uuid']},'source_sha256':hashlib.sha256(source_path.read_bytes()).hexdigest(),'prior_canceled_attempt_costs':failed['costs'],'bounds':{'read_bytes':20000000000,'write_remote_bytes':2500000000,'spill_to_disk_bytes':1000000000,'wall_s':400,'statement_cancel_after_s':90},'commits':[],'full_scope_rows':39990000,'selected_identity_interval':[8000001,10000001],'expected_selected_rows':expected}
 def save():(p/'summary.json').write_text(json.dumps(a,indent=2)+'\n')
 def metrics():
  for n in range(15):
   try:h=collect_history(c.w,c.records,p/'shared-history.json');break
   except HistoryPending:
    if n==14:raise
    time.sleep(2)
  a['costs']={k:sum(q['metrics'].get(k,0) for q in h.values()) for k in ['read_bytes','write_remote_bytes','spill_to_disk_bytes']};save();assert all(v<=a['bounds'][k] for k,v in a['costs'].items());assert time.monotonic()-start<400;return h
 def detail(table,label):
  rows=c.sql(label,'DESCRIBE DETAIL '+table);names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];return dict(zip(names,rows[0]))
 def bind(sid,label):
  rows=c.sql('history-'+label,'DESCRIBE HISTORY '+target+' LIMIT 20');names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];history=[dict(zip(names,r)) for r in rows];new=[r for r in history if r.get('queryHistoryStatementId')==sid];assert new;a['commits'].extend(new);assert {int(r['version']) for r in history}=={int(r['version']) for r in a['commits']}==set(range(int(history[0]['version'])+1));a['version']=int(history[0]['version']);save()
 try:
  save();assert detail(parent,'parent-detail')['id']==source['uuid'];c.sql('create',f"CREATE TABLE {target} USING DELTA PARTITIONED BY (lookup_partition) TBLPROPERTIES ('delta.targetFileSize'='67108864','delta.parquet.compression.codec'='zstd','delta.enableDeletionVectors'='true') AS SELECT {cols},{extra} AS lookup_partition FROM {parent} VERSION AS OF 4 WHERE false");bind(c.records[-1]['statement_id'],'create');c.sql('disable-maintenance','ALTER TABLE '+target+' DISABLE PREDICTIVE OPTIMIZATION');settings=c.sql('maintenance-setting','DESCRIBE TABLE EXTENDED '+target);assert [r[1] for r in settings if r[0]=='Predictive Optimization']==['DISABLE'];a['initial_detail']=detail(target,'initial-detail');a['uuid']=a['initial_detail']['id'];assert json.loads(a['initial_detail']['partitionColumns'])==['lookup_partition'];metrics();a['state']='Appending first2M identity interval';save();c.sql('append',f"INSERT INTO {target} ({cols},lookup_partition) SELECT {cols},{extra} FROM {parent} VERSION AS OF 4 WHERE id>=8000001 AND id<10000001");append_sid=c.records[-1]['statement_id'];bind(append_sid,'append');a['append_statement_id']=append_sid;metrics();a['state']='Auditing every first-stage carrier';save();hs=row_hash_sql(fields);rows=c.sql('full-field-digests',f"SELECT CAST(floor((id-8000001)/100000) AS BIGINT) group_id,count(*),sha2(concat_ws('',sort_array(collect_list({hs}))),256) FROM {target} VERSION AS OF {a['version']} GROUP BY group_id ORDER BY group_id");assert rows==want;a['groups']=rows;coverage=c.sql('coverage',f"SELECT count(*),count(DISTINCT struct(source_system,rel_type_id,id)),count_if(lookup_partition<>{extra} OR lookup_partition IS NULL),min(id),max(id) FROM {target} VERSION AS OF {a['version']}");assert int(coverage[0][0])==int(coverage[0][1])==expected and int(coverage[0][2])==0 and 8000001<=int(coverage[0][3])<=int(coverage[0][4])<10000001;a['coverage']=coverage;a['final_detail']=detail(target,'final-detail');assert a['final_detail']['id']==a['uuid'];metrics();a.update(state='First2M identity interval committed with complete20-field preservation',wall_s=time.monotonic()-start,qualification='Only first2M identity interval of intended39.99M graph. Exact20-field native digest groups match immutable full parent, candidate identity unique and physical partition exact-derived, underSHA256collision resistance. Prior canceled whole CREATE costs separately charged. No complete candidate, ZORDER, singleton/ingest/freshness or billion admission; remaining19intervals and full audit required. No ACK, cleanup, production pointer or compute change.');save();(p/'live-statement.json').unlink();print(a['state'],a['costs'])
 except Exception as exc:a.update(state='Stopped; inspect same handles without replay',error=str(exc),wall_s=time.monotonic()-start);save();raise
if __name__=='__main__':main()
