"""Continue19 disjoint source intervals into the owned range32 candidate; no blind replay."""
import json,time,hashlib
from pathlib import Path
from persistent_sql import Client
from publication_history import collect_history,HistoryPending
from mixed_change_queries_r230 import row_hash_sql
B=Path(__file__).resolve().parent

def main():
 prior_path=B/'out/native/ashlar_range32_stage_r313/audited-summary.json';prior=json.loads(prior_path.read_text());source_path=B/'out/native/ashlar_scoped_maintenance_r300/audited-summary.json';source=json.loads(source_path.read_text());assert prior['state']=='First2M identity interval committed with complete20-field preservation';assert hashlib.sha256(source_path.read_bytes()).hexdigest()==prior['source_sha256'];budget=json.loads((B/'out/range32-comparison-budget-r308.json').read_text());p=B/'out/native/ashlar_range32_grow_r314';assert not p.exists();p.mkdir();c=Client(p,observation_timeout=200,cancel_after=90);start=time.monotonic();t=prior['table'];fields=json.loads((B/'out/cdf-image-oracle-r288.json').read_text())['roles']['edge_current']['fields'];cols=','.join(fields);extra=budget['partition_expression'];hs=row_hash_sql(fields);a={'state':'Preflighting19remaining source intervals','table':t,'uuid':prior['uuid'],'parent':prior['parent'],'source_sha256':{'prior':hashlib.sha256(prior_path.read_bytes()).hexdigest(),'parent':hashlib.sha256(source_path.read_bytes()).hexdigest()},'bounds':{'read_bytes':200000000000,'write_remote_bytes':45000000000,'spill_to_disk_bytes':5000000000,'wall_s':1500,'statement_cancel_after_s':90},'commits':prior['commits'],'version':prior['version'],'stages':[],'groups':prior['groups'],'prior_attempt_costs':prior['audit']['aggregate_with_prior_canceled_full_create']}
 def save():(p/'summary.json').write_text(json.dumps(a,indent=2)+'\n')
 def metrics(reserve=0):
  for n in range(15):
   try:h=collect_history(c.w,c.records,p/'shared-history.json');break
   except HistoryPending:
    if n==14:raise
    time.sleep(2)
  a['costs']={k:sum(q['metrics'].get(k,0) for q in h.values()) for k in ['read_bytes','write_remote_bytes','spill_to_disk_bytes']};save();assert a['costs']['read_bytes']+reserve<=200000000000 and a['costs']['write_remote_bytes']<=45000000000 and a['costs']['spill_to_disk_bytes']<=5000000000;assert time.monotonic()-start<1500;return h
 def detail(label):
  rows=c.sql(label,'DESCRIBE DETAIL '+t);names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];d=dict(zip(names,rows[0]));assert d['id']==a['uuid'];return d
 def history(label):
  rows=c.sql(label,'DESCRIBE HISTORY '+t+' LIMIT 100');names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];return [dict(zip(names,r)) for r in rows]
 def check_ledger(rows):
  want={int(e['version']):e['queryHistoryStatementId'] for e in a['commits']};assert {int(e['version']):e['queryHistoryStatementId'] for e in rows}==want;assert set(want)==set(range(a['version']+1))
 try:
  save();detail('initial-detail');check_ledger(history('initial-history'));settings=c.sql('maintenance-setting','DESCRIBE TABLE EXTENDED '+t);assert [r[1] for r in settings if r[0]=='Predictive Optimization']==['DISABLE'];assert c.sql('initial-count',f"SELECT count(*) FROM {t} VERSION AS OF {a['version']}")==[[str(prior['expected_selected_rows'])]];metrics()
  for stage in range(1,20):
   metrics(10000000000);lo=8000001+stage*2000000;hi=lo+2000000;first=stage*20;want=source['checks']['after'][first:first+20];expected=sum(int(r[1]) for r in want);a['state']='Appending disjoint interval '+str(stage+1)+' of20';save();check_ledger(history('pre-history-'+str(stage)));c.sql('append-'+str(stage),f"INSERT INTO {t} ({cols},lookup_partition) SELECT {cols},{extra} FROM {a['parent']['table']} VERSION AS OF 4 WHERE id>={lo} AND id<{hi}");record=c.records[-1];sid=record['statement_id'];rows=history('post-history-'+str(stage));new=[e for e in rows if int(e['version'])>a['version']];assert new and all(e['queryHistoryStatementId']==sid and e['operation']=='WRITE' for e in new);assert sum(int(json.loads(e['operationMetrics'])['numOutputRows']) for e in new)==expected;a['commits'].extend(new);a['version']=int(rows[0]['version']);check_ledger(rows);save();metrics();actual=c.sql('digest-'+str(stage),f"SELECT CAST(floor((id-8000001)/100000) AS BIGINT) group_id,count(*),sha2(concat_ws('',sort_array(collect_list({hs}))),256) FROM {t} VERSION AS OF {a['version']} WHERE id>={lo} AND id<{hi} GROUP BY group_id ORDER BY group_id");assert actual==want;a['groups'].extend(actual);n=sum(int(r[1]) for r in a['groups']);assert c.sql('count-'+str(stage),f"SELECT count(*) FROM {t} VERSION AS OF {a['version']}")==[[str(n)]];a['stages'].append({'stage':stage,'identity_interval':[lo,hi],'rows':expected,'statement_id':sid,'version':a['version'],'append_caller_ms':record['wall_ms'],'groups':actual});detail('detail-'+str(stage));save();metrics()
  assert a['groups']==source['checks']['after'] and sum(int(r[1]) for r in a['groups'])==39990000;coverage=c.sql('partition-coverage',f"SELECT lookup_partition,count(*),count_if(lookup_partition<>{extra} OR lookup_partition IS NULL) FROM {t} VERSION AS OF {a['version']} GROUP BY lookup_partition ORDER BY lookup_partition");assert [int(r[0]) for r in coverage]==list(range(32)) and sum(int(r[1]) for r in coverage)==39990000 and all(int(r[2])==0 for r in coverage);a['partition_coverage']=coverage;a['final_detail']=detail('final-detail');metrics();a['aggregate_attempt_costs']={k:a['costs'][k]+a['prior_attempt_costs'][k] for k in a['costs']};a.update(state='All20source intervals populate full39.99M range32 candidate with complete carrier preservation',wall_s=time.monotonic()-start,qualification='19new2Midentity intervals plus independently qualified first interval;400complete20field multisets match immutable parent, exact full count and32derived partitions, underSHA256collision resistance. All actual commits accounted bySID; no unexplained outsidewrites. Full-field each-stage proof plus immutable ledger is not a general concurrent producer fence. Full ZORDER, repeated ingest publication, singleton/cold/concurrency and billion admission remain pending. No ACK, cleanup, pointer publication or compute resize.');save();(p/'live-statement.json').unlink();print(a['state'],a['costs'])
 except Exception as exc:a.update(state='Stopped; inspect original handles without replay',error=str(exc),wall_s=time.monotonic()-start);save();raise
if __name__=='__main__':main()
