"""Offline all-stage carrier and actual commit custody audit, before ZORDER."""
import json,hashlib
from pathlib import Path
B=Path(__file__).resolve().parent

def main():
 p=B/'out/native/ashlar_range32_grow_r314';a=json.loads((p/'summary.json').read_text());assert a['state']=='All20source intervals populate full39.99M range32 candidate with complete carrier preservation';prior_path=B/'out/native/ashlar_range32_stage_r313/audited-summary.json';parent_path=B/'out/native/ashlar_scoped_maintenance_r300/audited-summary.json';assert hashlib.sha256(prior_path.read_bytes()).hexdigest()==a['source_sha256']['prior'] and hashlib.sha256(parent_path.read_bytes()).hexdigest()==a['source_sha256']['parent'];prior=json.loads(prior_path.read_text());parent=json.loads(parent_path.read_text());records=[json.loads(x) for x in (p/'statements.jsonl').read_text().splitlines()];hh=json.loads((p/'shared-history.json').read_text());native={q['query_id']:q for q in hh['queries']};assert hh['require_final'] and not hh['missing_ids'] and len(native)==len(records)==len({r['statement_id'] for r in records})
 for r in records:
  q=native[r['statement_id']];assert q['is_final'] and q['status']=='FINISHED' and q['query_text']==r['sql'];assert r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
 def result(label):
  matches=[r for r in records if r['label']==label];assert len(matches)==1,label
  return matches[0]['response'].get('result',{}).get('data_array',[])
 assert len(a['stages'])==19 and a['groups']==parent['checks']['after'];assert sum(int(x[1]) for x in a['groups'])==39990000;assert a['uuid']==prior['uuid']==a['final_detail']['id'];assert [int(x[0]) for x in a['partition_coverage']]==list(range(32));assert a['partition_coverage']==result('partition-coverage') and sum(int(x[1]) for x in a['partition_coverage'])==39990000 and all(int(x[2])==0 for x in a['partition_coverage'])
 for stage in a['stages']:
  i=stage['stage'];lo=8000001+i*2000000;hi=lo+2000000;assert stage['identity_interval']==[lo,hi];expected=parent['checks']['after'][i*20:(i+1)*20];assert result('digest-'+str(i))==stage['groups']==expected;assert result('count-'+str(i))==[[str(sum(int(x[1]) for x in parent['checks']['after'][:(i+1)*20]))]];append=[r for r in records if r['statement_id']==stage['statement_id']];assert len(append)==1 and append[0]['label']=='append-'+str(i);events=[e for e in a['commits'] if e['queryHistoryStatementId']==stage['statement_id']];assert events and all(e['operation']=='WRITE' for e in events);assert sum(int(json.loads(e['operationMetrics'])['numOutputRows']) for e in events)==stage['rows'];assert not native[next(r for r in records if r['label']=='digest-'+str(i))['statement_id']]['metrics'].get('result_from_cache')
 assert len(a['commits'])==len({int(e['version']) for e in a['commits']}) and {int(e['version']) for e in a['commits']}==set(range(a['version']+1));assert a['costs']=={k:sum(q['metrics'].get(k,0) for q in native.values()) for k in a['costs']};assert all(v<=a['bounds'][k] for k,v in a['costs'].items()) and a['wall_s']<1500;a['audit']={'source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','shared-history.json']},'audit_script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'native_final_statements':len(records),'verified_new_intervals':19,'full_carrier_groups_including_prior':400,'qualified_rows':39990000,'qualification':a['qualification']};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['state'],a['costs'])
if __name__=='__main__':main()
