"""All32owned ZORDER stages and complete carrier/global integrity qualification."""
import json,time,hashlib
from pathlib import Path
from persistent_sql import Client
from publication_history import collect_history,HistoryPending
from mixed_change_queries_r230 import row_hash_sql
B=Path(__file__).resolve().parent

def main():
 source_path=B/'out/native/ashlar_range32_grow_r314/audited-summary.json';s=json.loads(source_path.read_text());assert s['state']=='All20source intervals populate full39.99M range32 candidate with complete carrier preservation';p=B/'out/native/ashlar_range32_maintain_r316';assert not p.exists();p.mkdir();c=Client(p,observation_timeout=200,cancel_after=90);start=time.monotonic();t=s['table'];fields=json.loads((B/'out/cdf-image-oracle-r288.json').read_text())['roles']['edge_current']['fields'];hs=row_hash_sql(fields);first=json.loads((B/'out/native/ashlar_range32_stage_r313/audited-summary.json').read_text());canceled=json.loads((B/'out/native/ashlar_range32_build_r309/summary.json').read_text());prior_wall=s['wall_s']+first['wall_s']+canceled['wall_s'];a={'state':'Preflighting full32partition maintenance','source_sha256':hashlib.sha256(source_path.read_bytes()).hexdigest(),'table':t,'uuid':s['uuid'],'version':s['version'],'commits':s['commits'],'stages':[],'bounds':{'read_bytes':250000000000,'write_remote_bytes':40000000000,'spill_to_disk_bytes':5000000000,'wall_s':1800,'statement_cancel_after_s':90,'combined_phase_wall_s':2400,'aggregate_attempt_read_bytes':600000000000,'aggregate_attempt_write_bytes':120000000000},'prior_phase_wall_s':prior_wall,'prior_attempt_costs':s['aggregate_attempt_costs']}
 def save():(p/'summary.json').write_text(json.dumps(a,indent=2)+'\n')
 def metrics(read_reserve=0,write_reserve=0):
  for n in range(15):
   try:h=collect_history(c.w,c.records,p/'shared-history.json');break
   except HistoryPending:
    if n==14:raise
    time.sleep(2)
  a['costs']={k:sum(q['metrics'].get(k,0) for q in h.values()) for k in ['read_bytes','write_remote_bytes','spill_to_disk_bytes']};save();assert a['costs']['read_bytes']+read_reserve<=250000000000 and a['costs']['write_remote_bytes']+write_reserve<=40000000000 and a['costs']['spill_to_disk_bytes']<=5000000000;assert a['prior_attempt_costs']['read_bytes']+a['costs']['read_bytes']+read_reserve<=600000000000 and a['prior_attempt_costs']['write_remote_bytes']+a['costs']['write_remote_bytes']+write_reserve<=120000000000;assert time.monotonic()-start<1800 and prior_wall+time.monotonic()-start<2400;return h
 def detail(label):
  rows=c.sql(label,'DESCRIBE DETAIL '+t);names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];d=dict(zip(names,rows[0]));assert d['id']==a['uuid'];return d
 def history(label):
  rows=c.sql(label,'DESCRIBE HISTORY '+t+' LIMIT 100');names=[x['name'] for x in c.records[-1]['response']['manifest']['schema']['columns']];return [dict(zip(names,r)) for r in rows]
 def ledger(rows):
  assert {int(r['version']):r['queryHistoryStatementId'] for r in rows}=={int(r['version']):r['queryHistoryStatementId'] for r in a['commits']};assert {int(r['version']) for r in rows}==set(range(a['version']+1))
 try:
  save();a['initial_detail']=detail('initial-detail');assert json.loads(a['initial_detail']['partitionColumns'])==['lookup_partition'] and json.loads(a['initial_detail']['clusteringColumns'])==[];ledger(history('initial-history'));setting=c.sql('maintenance-setting','DESCRIBE TABLE EXTENDED '+t);assert [r[1] for r in setting if r[0]=='Predictive Optimization']==['DISABLE'];metrics()
  for bucket in range(32):
   metrics(8000000000,2000000000);ledger(history('pre-history-'+str(bucket)));a['state']='ZORDER partition '+str(bucket)+' of32';save();c.sql('optimize-'+str(bucket),f'OPTIMIZE {t} WHERE lookup_partition={bucket} ZORDER BY (lookup_hash)');r=c.records[-1];sid=r['statement_id'];history_rows=history('post-history-'+str(bucket));new=[e for e in history_rows if int(e['version'])>a['version']];assert new and all(e['queryHistoryStatementId']==sid and e['operation']=='OPTIMIZE' for e in new);a['commits'].extend(new);a['version']=int(history_rows[0]['version']);ledger(history_rows);a['stages'].append({'partition':bucket,'statement_id':sid,'versions':[int(e['version']) for e in new],'caller_ms':r['wall_ms']});save();metrics()
  a['state']='Auditing all39.99M carriers after32maintenance stages';save();groups=[]
  for first_group in range(0,400,100):
   metrics(40000000000);lo=8000001+first_group*100000;hi=lo+10000000;rows=c.sql('digest-'+str(first_group),f"SELECT CAST(floor((id-8000001)/100000) AS BIGINT) group_id,count(*),sha2(concat_ws('',sort_array(collect_list({hs}))),256) FROM {t} VERSION AS OF {a['version']} WHERE id>={lo} AND id<{hi} GROUP BY group_id ORDER BY group_id");assert rows==s['groups'][first_group:first_group+100];groups.extend(rows);save()
  assert groups==s['groups'];a['groups']=groups;extra=json.loads((B/'out/range32-comparison-budget-r308.json').read_text())['partition_expression'];coverage=c.sql('coverage',f"SELECT count(*),count(DISTINCT struct(source_system,rel_type_id,id)),count_if(lookup_partition<>{extra} OR lookup_partition IS NULL) FROM {t} VERSION AS OF {a['version']}");assert coverage==[['39990000','39990000','0']];a['coverage']=coverage
  qualified=json.loads((B/'out/native/ashlar_scale_edges_r274/audited-summary.json').read_text());node=qualified['tables']['object_current'];F='client_dev.ashlar_entropy_20261006_r86';edge=f"{t} VERSION AS OF {a['version']}";assert c.sql('deleted-absent',f'SELECT count(*) FROM {edge} e INNER JOIN {F}.mixed_tombstone_r281 VERSION AS OF 1 d ON e.source_system=d.source_system AND e.rel_type_id=d.type_id AND e.id=d.id')==[['0']];assert c.sql('typed-endpoints',f"SELECT count(*),count_if(n1.id IS NULL OR n2.id IS NULL) FROM {edge} e LEFT JOIN {node['table']} VERSION AS OF {node['version']} n1 ON e.source_system=n1.source_system AND e.source_type=n1.type_id AND e.source_id=n1.id LEFT JOIN {node['table']} VERSION AS OF {node['version']} n2 ON e.source_system=n2.source_system AND e.target_type=n2.type_id AND e.target_id=n2.id")==[['39990000','0']];a['global_integrity']='Unique typed native edge identities, exact partitions, known deletions absent and both typed endpoints closed';a['final_detail']=detail('final-detail');metrics();a.update(state='Full39.99M range32 current candidate preserves all20carrier fields',wall_s=time.monotonic()-start,combined_phase_wall_s=prior_wall+time.monotonic()-start,aggregate_attempt_costs={k:a['costs'][k]+a['prior_attempt_costs'][k] for k in a['costs']},qualification='All32partition ZORDER stages and whole400group20-field carrier equality to qualified full parent; final unique native identity, exact partition mapping, deleted absence and typed endpoint closure pass underSHA256collision resistance. All actual commits including multi-commit operations accounted bySID; private controlled writer custody only. Direct graph feature admission, native singleton/cold/concurrency, subsequent ingest/freshness and billion admission remain unproved. No ACK, cleanup, production pointer or compute resize.');save();(p/'live-statement.json').unlink();print(a['state'],a['costs'])
 except Exception as exc:a.update(state='Stopped; inspect existing handles without replay',error=str(exc),wall_s=time.monotonic()-start);save();raise
if __name__=='__main__':main()
