"""Saved-evidence clone/setup cost attribution; no new native workload."""
import hashlib,json
from pathlib import Path
B=Path(__file__).resolve().parent

def main():
 p=B/'out/native/ashlar_incremental_publish_r332';a=json.loads((p/'audited-summary.json').read_text());records=[json.loads(x) for x in (p/'statements.jsonl').read_text().splitlines()];native={q['query_id']:q for q in json.loads((p/'shared-history.json').read_text())['queries']}
 for name,h in a['audit']['source_sha256'].items():assert hashlib.sha256((p/name).read_bytes()).hexdigest()==h
 def group(labels):
  rs=[r for r in records if r['label'] in labels];assert len(rs)==len(labels) and len({r['label'] for r in rs})==len(labels)
  for r in rs:assert native[r['statement_id']]['status']=='FINISHED' and native[r['statement_id']]['is_final'] and native[r['statement_id']]['query_text']==r['sql']
  return {'statements':[{'label':r['label'],'statement_id':r['statement_id'],'caller_s':r['wall_ms']/1000,'engine_ms':native[r['statement_id']]['metrics'].get('execution_time_ms',0)} for r in rs],'serial_caller_sum_s':sum(r['wall_ms']/1000 for r in rs),'costs':{k:sum(native[r['statement_id']]['metrics'].get(k,0) for r in rs) for k in ['read_bytes','write_remote_bytes','spill_to_disk_bytes']}}
 roles=['edge_current','source_record','property_journal','adjacency_forward'];clones=group(['clone-'+r for r in roles]);assert all('SHALLOW CLONE' in r['sql'] and 'VERSION AS OF' in r['sql'] for r in records if r['label'] in ['clone-'+role for role in roles]);settings=group(['disable-'+r for r in roles]+['enable-cdf-edge_current','enable-cdf-adjacency_forward','disable-tombstone']);replay=group(['prepare-first-source_record','prepare-first-property_journal','prepare-first-tombstone','prepare-first-forward']);creation=group(['create-tombstone','create-manifest']);capacity=B/'out/capacity-observed-r268.json';cap=json.loads(capacity.read_text())
 out={'format':'ashlar-role-isolation-cost-attribution/1','source_sha256':{'out/native/ashlar_incremental_publish_r332/audited-summary.json':hashlib.sha256((p/'audited-summary.json').read_bytes()).hexdigest(),'out/capacity-observed-r268.json':hashlib.sha256(capacity.read_bytes()).hexdigest()},'four_clones':clones,'settings':settings,'fixture_first_batch_replay':replay,'empty_tombstone_manifest_creation':creation,'full_preparation_s':a['preparation_s'],'full_processing_s':a['processing_s'],'whole_run_s':a['wall_s'],'whole_run_costs':a['costs'],'arrival_window_for100k_at10k_s':10,'clone_only_serial_service_sensitivity_entities_per_s':100000/clones['serial_caller_sum_s'],'planning_scale':{'nodes':1000000000,'edges':5000000000,'active_bytes_arithmetic':cap['total']['scaled_active_bytes'] if 'total' in cap else cap['totals']['scaled_active_bytes'],'ideal64MiB_file_arithmetic':211134,'journal_rows_assumed':cap['bootstrap_journal_rows_assumed']},'qualification':'One measured serialized fixture. Clone sum excludes metadata validation/settings/history/first-batch reconstruction, not a counterfactual production latency or clone-per-batch requirement. No new workload or concurrency measurement. Service division repeats one sample, not sustained capacity. Capacity remains original r268 arithmetic, excludes retained/duplicate attempts, metadata and real costs; no clone speed/file count extrapolation to1B/5B.'}
 (B/'out/role-isolation-cost-r373.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'clone_s':clones['serial_caller_sum_s'],'settings_s':settings['serial_caller_sum_s'],'fixture_replay_s':replay['serial_caller_sum_s'],'creation_s':creation['serial_caller_sum_s'],'clone_costs':clones['costs']},indent=2))
if __name__=='__main__':main()
