"""Role-wise storage sensitivity from immutable recorded native samples."""
import json,hashlib,math
from pathlib import Path
B=Path(__file__).resolve().parent
S=['out/native/ashlar_entropy_20261006_r86/audited-summary.json','out/native/ashlar_entropy_publication_20261006_r89/audited-summary.json','scale_workload.py','entropy_publication.py']
def calculate():
 baseline=json.loads((B/S[0]).read_text());pub=json.loads((B/S[1]).read_text());roles={}
 for kind,count in [('object',4000000),('edge',20000000)]:
  d=baseline['tables'][kind];roles[kind+'_current']={'sample_rows':count,'sample_bytes':d['bytes'],'sample_files':d['files'],'compressed_bytes_per_row':d['bytes']/count,'double_scale_same_width_bytes':d['bytes']*2,'double_scale_same_fill_files':d['files']*2}
 for kind in ['source_record','property_journal']:
  d=pub['durable_table_details'][kind];width=int(d['sizeInBytes'])/pub['changed_edges'];roles[kind]={'sample_rows':pub['changed_edges'],'sample_bytes':int(d['sizeInBytes']),'compressed_bytes_per_event':width,'one_day_at_10k_entity_changes_per_s_same_event_width_bytes':width*10000*86400}
 current=sum(x['double_scale_same_width_bytes'] for k,x in roles.items() if k.endswith('_current'))
 return {'format':'ashlar-role-accounting-sensitivity/1','source_sha256':{n:hashlib.sha256((B/n).read_bytes()).hexdigest() for n in S},'roles':roles,'8m_40m_current_only_bytes':current,'proposed140gb_cap_remaining_before_other_roles_bytes':140000000000-current,'first_touch':{'changed_rows':pub['changed_edges'],'native_merge_execution_ms':int(pub['edge_merge_metrics']['executionTimeMs']),'caller_ms':next(x['caller_ms'] for x in pub['phases'] if x['label']=='apply-current'),'baseline_files':baseline['tables']['edge']['files'],'deletion_vectors_added':int(pub['edge_merge_metrics']['numTargetDeletionVectorsAdded']),'updated_id_formula':'pmod(id*104729,20000000)+1 for generator ordinal0..199999','qualification':'Distinct deterministic scattered IDs, not random draws. First property107 insertion differs from later property105 replacement and source shape; timing ratio is not causal proof.'},'admission':'Not admitted: complete-role source/history bootstrap, semantic corpus, retention and integrity I/O estimates remain unproved. Current81.423GB arithmetic is not full graph storage.','required_unknowns':['Full initial raw source for every node/edge, including source framing and byte distribution. Historical baseline origins unavailable.','Property-event fanout per entity and exact before/after token widths. Boolean107 event12.684 bytes compressed is not arbitrary value history.','Append retention horizon, checkpoints/log/DVs, failed uncommitted work and shared baseline shallow-clone dependencies.','Forward/reverse projection selections, tombstone/churn distribution and temporary staging overlap.','Complete range-wise exact integrity costs and endpoint checks at8M/40M; cached full scans are not a cost guarantee.','Actual marginal billing and storage pricing; compute inventory alone cannot price experiment.'],'design_implication':'Retain independently priced current/raw/property-journal/manifest roles and publication pins. Do not coalesce or truncate retained source/history to satisfy a current-table cap. Choose retention with consumer recovery/ack requirements; no expiry or VACUUM decision in this sensitivity.'}
if __name__=='__main__':
 r=calculate();(B/'out/role-accounting-r214.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r,indent=2))
