"""Reproducible staged resource proposal; no complete-graph admission."""
import json,hashlib
from pathlib import Path
B=Path(__file__).resolve().parent
S=['out/native-complete-storage-r227.json','out/mixed-role-costs-r235.json','out/native/ashlar_scale_slice_r236/summary.json']
def calculate():
 base,cost,slice_=[json.loads((B/n).read_text()) for n in S];assert slice_['state']=='First200k-node complete-role growth slice passes every independent row digest'
 # Margins are explicit planning choices, not measured future consumption.
 components={'bootstrap_same_width_1_5x':base['same_width_8m_40m_total_bytes']*1.5,'four_100k_change_batches_1_5x':cost['one_100k_batch_same_width_active_increment_bytes']*4*1.5,'four_100k_input_stages_1_5x':cost['stage_bytes_per_changed_entity']*400000*1.5,'additional_retained_file_overlap_assumed':20000000000,'one_failed_phase_work_assumed':8000000000,'logs_checkpoints_DVs_controls_and_background_margin_assumed':10000000000}
 total=sum(components.values());cap=220000000000
 return {'format':'ashlar-staged-scale-resource-proposal/1','source_sha256':{n:hashlib.sha256((B/n).read_bytes()).hexdigest() for n in S},'planned_graph':{'nodes':8000000,'edges':40000000},'owner_final_scale':{'nodes':1000000000,'edges':5000000000},'components':components,'proposed_cumulative_write_work_and_new_storage_ceiling_bytes':cap,'estimated_components_bytes':total,'unallocated_margin_bytes':cap-total,'status':'Proposed220GB replaces insufficient140GB sensitivity; not a bulk-run admission or monetary cap. Only recorded200k-node slice executed.','next_node_slice':{'start':200000,'end':400000,'reported_read_ceiling':10000000000,'reported_write_ceiling':2000000000,'statement_wall_s':180,'whole_slice_wall_s':900,'remaining_nodes_after_execution':7600000},'controls':['Verify current target UUIDs, prior logical range membership and exact committed versions; do not require physical head equality.','Use explicitly bound INSERT column names for complete current/raw/property roles; no partial publication.','Persist statement IDs and same-handle terminal recovery; failed/unknown work counts against reserves before another slice.','Keep independent Python full-field range digests and exact native range/cardinality checks; bound digest aggregation to slice size.','Reserve estimates include retained-source/history roles, but background work and physical retained-version bytes still require inventory.','Only after all8M node ranges and40M edge ranges/adjacency complete and typed endpoints pass may a graph descriptor advance.','Record actual emitted file sizes/statistics; staging r236 did not set64MiB target and emits162–169MB files. Future canonical target profile needs separate measurement.','Enforce per-slice ceilings and aggregate owned work before each admission. A native phase can overrun before final telemetry; stop growth, retain exact evidence, never erase failed-work costs.','Full-run wall/price envelope is unqualified. Per-slice15min ceiling is not permission for indefinitely accumulating compute time.'],'limits':['1.5x widths and20/8/10GB reserves are declared planning assumptions, not native measurements at8M/40M.','200k slice verifies only first node range; no complete8M graph, edge scale or latency/ingest admission.','No expiry/VACUUM or source ACK inferred. Retained failed/bootstrap/stage tables remain additional existing inventory.','No new compute or resize; current RUNNING2XSmall serverless data-gateway snapshot is not marginal billing evidence.']}
if __name__=='__main__':
 r=calculate();(B/'out/scale-reserves-r237.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'components':r['components'],'estimated_components_bytes':r['estimated_components_bytes'],'unallocated_margin_bytes':r['unallocated_margin_bytes'],'status':r['status']},indent=2))
