"""Qualified input-content audit with one explicitly truncated native SQL text."""
import hashlib,json
from pathlib import Path
B=Path(__file__).resolve().parent

def main():
 p=B/'out/native/ashlar_sixth_delta_stage_r533';a=json.loads((p/'summary.json').read_text());assert a['state']=='Four complete normalized input roles match independent source digests and are Delta-version pinned';source=B/'out/native/ashlar_sixth_batch_upload_r531/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());rs=list(map(json.loads,(p/'statements.jsonl').read_text().splitlines()));h=json.loads((p/'shared-history.json').read_text());native={q['query_id']:q for q in h['queries']};assert h['require_final'] and not h['missing_ids'] and len(rs)==len(native)==len({r['statement_id'] for r in rs})==36;by={r['label']:r for r in rs};rows=lambda label:by[label]['response']['result']['data_array']
 for r in rs:
  q=native[r['statement_id']];assert q['status']=='FINISHED' and q['is_final'] and (q['query_text']==r['sql'] or (r['label']=='create-source_record' and q['query_text']==r['sql'][:1024]+'...')) and r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
  if r['label'].startswith(('verify-','sixth-batch-')):assert not q['metrics'].get('result_from_cache')
 for role,t in a['tables'].items():
  expected=s['roles'][role];assert rows('verify-'+role)==[[str(expected['rows']),expected['original_input_multiset_digest'],expected['all_known_field_digest']]];assert t['version']==0 and t['statement_id']==by['create-'+role]['statement_id']==t['history']['queryHistoryStatementId'];assert a['checks'][role]['fields']==expected['fields'];d=by['detail-'+role];cols=[c['name'] for c in d['response']['manifest']['schema']['columns']];assert dict(zip(cols,rows('detail-'+role)[0]))['id']==t['id'];assert rows('sixth-batch-'+role)==[['0']]
 assert rows('raw-unique-and-digests')==[['100000','100000','0']] and rows('replacement-identity')==[['90000','90000','0']] and rows('deletion-identity')==[['10000','10000','0']] and rows('journal-identity')==[['216667','216667','0']] and rows('change-partition')==[['100000','90000','10000','0']]
 for role in ['property_journal','tombstone','current_replacement']:assert rows('raw-link-'+role)==[[str(s['roles'][role]['rows']),'0']]
 costs={k:sum(q['metrics'].get(k,0) for q in native.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<a['bounds']['wall_s'];a['audit']={'native_final_statements':36,'native_full_sql_matches':35,'native_prefix_only_statement':by['create-source_record']['statement_id'],'sql_text_qualification':'One17446-character submitted CTAS has native1024-character prefix plus ellipsis; exact full server SQL is unproved. Full input original-text/known-field digests, unique identities and actual UUID/version0/SID bindings qualify contents independently. R534 stricter audit stopped; R538 system-history observation returned no row and does not recover full text.','source_receipt_as_used':str(source.relative_to(B)),'source_receipt_note':'Transfer receipt is the complete frozen sixth-batch native SHA/byte audit used at staging.','source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','shared-history.json']},'qualified_input_checks_uncached':True,'qualification':a['qualification']};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');assert sum(native[r['statement_id']]['query_text']==r['sql'] for r in rs)==35;live=json.loads((p/'live-statement.json').read_text());assert live['statement_id'] in native;(p/'live-statement.json').rename(p/'completed-last-statement.json');print(a['audit'])
if __name__=='__main__':main()
