"""Independent native final and full changed-file EXCEPT ALL preservation audit."""
import json,hashlib
from pathlib import Path
from overlay_sql_r395 import FIELDS
B=Path(__file__).resolve().parent;p=B/'out/native/ashlar_sparse_maintain_r610';a=json.loads((p/'summary.json').read_text());assert a['state']=='Sparse maintenance complete with exact changed-file carrier parity and physical common-file custody';source=B/'out/native/ashlar_sparse_baseline_r608/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());assert a['table']==s['table'] and a['scope']==s['scope'];inv=json.loads((B/'out/native/ashlar_current_file_ranges_r606/summary.json').read_text());rs=list(map(json.loads,(p/'statements.jsonl').read_text().splitlines()));h=json.loads((p/'shared-history.json').read_text());qs={q['query_id']:q for q in h['queries']};assert len(rs)==len(qs)==len({r['statement_id'] for r in rs})==12 and h['require_final'] and not h['missing_ids'];by={r['label']:r for r in rs}
def rows(label):return by[label]['response'].get('result',{}).get('data_array',[])
def objs(label):return [dict(zip([x['name'] for x in by[label]['response']['manifest']['schema']['columns']],r)) for r in rows(label)]
for r in rs:
 q=qs[r['statement_id']];assert q['status']=='FINISHED' and q['is_final'] and q['query_text']==r['sql'] and r['response']['status']['state']=='SUCCEEDED' and not r['response'].get('manifest',{}).get('truncated')
assert rows('files-after')==a['after_files'];old={r[0]:r for r in inv['files']};new={r[0]:r for r in a['after_files']};assert len(new)==len(a['after_files']) and sum(int(r[2]) for r in new.values())==39930000;assert all(old[k]==new[k] for k in set(old)&set(new));removed=sorted(set(old)-set(new));added=sorted(set(new)-set(old));assert a['removed_files']==[old[k] for k in removed] and a['added_files']==[new[k] for k in added]
t=a['table'];v=a['after_version'];assert int(objs('head-before')[0]['version'])==10;commits=[x for x in objs('history-after') if int(x['version'])>10];assert commits==a['commits']==[x for x in objs('final-head') if int(x['version'])>10] and [int(x['version']) for x in commits]==list(range(v,10,-1));assert all(x['operation']=='OPTIMIZE' and x['queryHistoryStatementId']==by['optimize']['statement_id']==a['optimize_statement_id'] for x in commits);assert by['optimize']['sql']=='OPTIMIZE '+t['table']+' FULL WHERE '+a['predicate']
def relation(version,paths):
 literals=','.join("decode(unhex('"+k.encode().hex()+"'),'UTF-8')" for k in paths)
 return 'SELECT '+','.join(FIELDS)+f" FROM {t['table']} VERSION AS OF {version} WHERE "+('_metadata.file_path IN ('+literals+')' if paths else 'false')
before=relation(10,removed);after=relation(v,added)
for label,left,right in [('removed-minus-added',before,after),('added-minus-removed',after,before)]:assert by[label]['sql']=='SELECT count(*) FROM (('+left+') EXCEPT ALL ('+right+'))' and rows(label)==[['0']] and not qs[by[label]['statement_id']]['metrics'].get('result_from_cache')
assert rows('maintenance-cdf')==[['0']] and objs('schema-before')==objs('schema-after');assert objs('detail-before')[0]['id']==objs('detail-after')[0]['id']==t['id'];costs={k:sum(q['metrics'].get(k,0) for q in qs.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<600;a['audit']={'native_final_statements':len(rs),'removed_files':len(removed),'added_files':len(added),'shared_files':len(set(old)&set(new)),'complete_changed_file_carrier_parity':True,'qualification':a['qualification'],'receipt_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','shared-history.json']}};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['audit'])
