"""Offline native-final stale-role custody and pinned-carrier audit."""
import hashlib,json
from pathlib import Path
from scale_mixed_r219 import Workload
B=Path(__file__).resolve().parent

def main():
 p=B/'out/native/ashlar_stale_role_barrier_r374';a=json.loads((p/'summary.json').read_text());assert a['state']=='40M-edge private stale commit refused; parent manifest and exact old carrier preserved';rs=[json.loads(x) for x in (p/'statements.jsonl').read_text().splitlines()];native={q['query_id']:q for q in json.loads((p/'query-history.json').read_text())};assert len(rs)==len(native)==len({r['statement_id'] for r in rs});by={r['label']:r for r in rs}
 for r in rs:
  q=native[r['statement_id']];assert q['is_final'] and q['status']=='FINISHED' and r['response']['status']['state']=='SUCCEEDED' and q['query_text']=='/* ashlar '+p.name+' '+r['label']+' */ '+r['sql'] and not q['metrics'].get('result_from_cache')
 source=B/'out/native/ashlar_scale_edges_r274/audited-summary.json';assert hashlib.sha256(source.read_bytes()).hexdigest()==a['source_sha256'];s=json.loads(source.read_text());assert a['parent']==s['tables']['edge_current'];assert by['clone']['sql']==f'CREATE TABLE {a["table"]} SHALLOW CLONE {a["parent"]["table"]} VERSION AS OF 8';assert a['clone_statement_id']==by['clone']['statement_id'] and a['injected_statement_id']==by['injected-role-write']['statement_id'];assert a['approved_role_statement_ids']==[a['clone_statement_id']]
 row=Workload(8000000,40000000).carrier('edge',a['ordinal']);fields=list(row);expected=[[None if row[f] is None else row[f].replace('T',' ').removesuffix('Z') if f=='published_at' else row[f] for f in fields]]
 for label in ['before-old-pin','after-old-pin']:
  r=by[label];assert r['response']['result']['data_array']==expected and 'VERSION AS OF 0 WHERE lookup_hash=:hash AND source_system=:source' in r['sql']
 changed=json.loads(json.dumps(expected));changed[0][fields.index('retained_json')]=a['marker'];assert by['contaminated-head']['response']['result']['data_array']==changed and 'VERSION AS OF 1' in by['contaminated-head']['sql'];assert by['injected-role-write']['parameters']==dict(by['before-old-pin']['parameters'],marker=a['marker']) and 'SET retained_json=:marker' in by['injected-role-write']['sql']
 assert [int(c['version']) for c in a['after_role_history']]==[1,0];assert a['after_role_history'][0]['queryHistoryStatementId']==a['injected_statement_id'] and a['after_role_history'][0]['operation']=='UPDATE';assert a['after_role_history'][1]['queryHistoryStatementId']==a['clone_statement_id'];assert a['publication_refusal']=='unapproved role commit' and a['manifest_before']==a['manifest_after'];assert [int(c['version']) for c in a['manifest_after']]==[1,0];assert {c['queryHistoryStatementId'] for c in a['manifest_after']}=={by['create-manifest']['statement_id'],by['parent-publication']['statement_id']}
 text=json.dumps(a['descriptor'],sort_keys=True,separators=(',',':'));assert text==a['canonical_descriptor'] and hashlib.sha256(text.encode()).hexdigest()==a['descriptor_sha256'];vector=a['descriptor']['vector'];assert vector['edge_current']['id']==a['detail']['id'] and vector['edge_current']['version']==0 and all(vector[k]==v for k,v in s['tables'].items() if k!='edge_current');assert by['unchanged-manifest']['response']['result']['data_array']==[[a['descriptor']['id'],text,a['descriptor_sha256']]]
 costs={k:sum(q['metrics'].get(k,0) for q in native.values()) for k in a['costs']};assert costs==a['costs'] and all(v<=a['bounds'][k] for k,v in costs.items()) and a['wall_s']<a['bounds']['wall_s'];a['audit']={'native_final_statements':len(rs),'full_fields_per_point':20,'original_pin_reads':2,'contaminated_pin_reads':1,'source_sha256':{n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in ['summary.json','statements.jsonl','query-history.json']},'qualification':a['qualification']};(p/'audited-summary.json').write_text(json.dumps(a,indent=2)+'\n');print(a['audit'])
if __name__=='__main__':main()
