"""Native adversarial controls evaluate the exact shared publication predicate."""
import json
from pathlib import Path
from driver_sql import DriverClient
from edge_fused_guard import COLS,post
B=Path(__file__).resolve().parent;F='client_dev.ashlar_composite_edges_20261005_q1';out=B/'out/native/ashlar_edge_fused_guard_20261005_r17';c=DriverClient(out)
replace={'props_json':'s.new_props','entity_version':'cast(7 AS BIGINT)','source_feed':"'fixture-fused300k'",'source_epoch':"'e'",'source_position':'cast(1 AS BIGINT)','published_at':'current_timestamp()'}
e=','.join(replace.get(x,'s.'+x)+' AS '+x for x in COLS)
old="to_json(array(get_json_object(s.props_json,'$.201')))";new="to_json(array(get_json_object(s.new_props,'$.201')))"
common=f"""s AS (SELECT *, '{{"201":"control"}}' new_props,id ordinal FROM {F}.edge_current VERSION AS OF 13 WHERE source_system='pilot:0' AND rel_type_id=7 AND id=120001),e0 AS (SELECT {e} FROM s),j0 AS (SELECT source_system,'edge' entity_kind,rel_type_id type_id,id,201 property_id,7 entity_version,'update' operation,true old_present,substring({old},2,length({old})-2) old_json,true new_present,substring({new},2,length({new})-2) new_json,schema_revision,'fixture-fused300k' source_feed,'e' source_epoch,1 source_position,ordinal event_ordinal,'synthetic-fused:1' source_time_text,current_timestamp() published_at FROM s)"""
cases={'clean':('SELECT * FROM e0','SELECT * FROM j0'), 'missing-canonical':('SELECT * FROM e0 WHERE false','SELECT * FROM j0'),'duplicate-canonical':('SELECT * FROM e0 UNION ALL SELECT * FROM e0','SELECT * FROM j0'),'wrong-bag':("SELECT * EXCEPT(props_json),cast(NULL AS STRING) props_json FROM e0",'SELECT * FROM j0'),'wrong-endpoint':('SELECT * EXCEPT(target_id),target_id+1 target_id FROM e0','SELECT * FROM j0'),'lost-retained':('SELECT * EXCEPT(retained_json),cast(NULL AS STRING) retained_json FROM e0','SELECT * FROM j0'),'wrong-hash':("SELECT * EXCEPT(lookup_hash),'bad' lookup_hash FROM e0",'SELECT * FROM j0'),'wrong-version':('SELECT * EXCEPT(entity_version),6 entity_version FROM e0','SELECT * FROM j0'),'missing-journal':('SELECT * FROM e0','SELECT * FROM j0 WHERE false'),'duplicate-journal':('SELECT * FROM e0','SELECT * FROM j0 UNION ALL SELECT * FROM j0'),'wrong-old-value':('SELECT * FROM e0',"SELECT * EXCEPT(old_json),'null' old_json FROM j0"),'wrong-presence':('SELECT * FROM e0','SELECT * EXCEPT(old_present),false old_present FROM j0'),'wrong-source-time':('SELECT * FROM e0',"SELECT * EXCEPT(source_time_text),'wrong' source_time_text FROM j0")}
for label,(ce,cj) in cases.items():
 q=f"WITH {common},e AS ({ce}),j AS ({cj}) SELECT count(*)<>1 OR count(DISTINCT struct(s.source_system,s.rel_type_id,s.id))<>1 OR count_if({post(1)})<>0 FROM s JOIN e ON s.source_system=e.source_system AND s.rel_type_id=e.rel_type_id AND s.id=e.id LEFT JOIN j ON s.source_system=j.source_system AND s.rel_type_id=j.type_id AND s.id=j.id AND j.source_feed='fixture-fused300k' AND j.source_position=1"
 r=c.sql(label,q);assert len(r)==1 and r[0][0].lower()==('false' if label=='clean' else 'true'),(label,r)
(out/'summary.json').write_text(json.dumps({'state':'passed','controls':list(cases),'scope':'exact shared predicate, 13 virtual native cases; no table changes'},indent=2));c.history();c.close();print('Shared fused guard controls passed')
