"""Full final carrier and journal checks for terminal scheduled batches."""
import json
from pathlib import Path
from driver_sql import DriverClient
B=Path(__file__).resolve().parent;F='client_dev.ashlar_composite_edges_20261005_q1';s=json.loads((B/'out/native/ashlar_fenced_scheduled_20261005_r13r1/summary.json').read_text());assert s['state']=='completed';out=B/'out/native/ashlar_fenced_scheduled_verify_20261005_r13r1';c=DriverClient(out);last=s['batches'][-1]['versions'];ev=last[F+'.edge_current'];jv=last[F+'.property_journal']
cols=['source_system','rel_type_id','id','source_type','source_id','target_type','target_id','schema_revision','entity_version','props_json','retained_json','order_key','source_feed','source_epoch','source_position','published_at','lookup_hash'];key=lambda a,b:' AND '.join(f'{a}.{x}={b}.{x}' for x in ['source_system','rel_type_id','id'])
stages=' UNION ALL '.join(f'SELECT *,{i} batch FROM {F}.stage_r13r1_{i}' for i in range(1,5))
assert c.sql('final-identities',f'SELECT count(*),count(DISTINCT struct(source_system,rel_type_id,id)) FROM {F}.edge_current VERSION AS OF {ev}')==[['10019981','10019981']]
diff=' OR '.join(f'o.{x} IS DISTINCT FROM e.{x}' for x in cols)
assert c.sql('untouched-all17',f'WITH stages AS ({stages}) SELECT count(*),count_if({diff}) FROM {F}.edge_current VERSION AS OF 6 o JOIN {F}.edge_current VERSION AS OF {ev} e ON {key("o","e")} LEFT ANTI JOIN stages t ON {key("o","t")}')==[['9219981','0']]
assert c.sql('journal-origins',f"SELECT count(*),count(DISTINCT struct(source_feed,source_epoch,source_position,event_ordinal)) FROM {F}.property_journal VERSION AS OF {jv} WHERE source_feed='fixture-scheduled-fenced'")==[['800000','800000']]
checks=["j.entity_kind IS DISTINCT FROM 'edge'","j.property_id IS DISTINCT FROM 201","j.entity_version IS DISTINCT FROM 5","j.operation IS DISTINCT FROM 'update'","j.old_present IS DISTINCT FROM true","j.new_present IS DISTINCT FROM true","j.schema_revision IS DISTINCT FROM s.schema_revision","j.event_ordinal IS DISTINCT FROM s.ordinal","j.source_epoch IS DISTINCT FROM 'e'","j.published_at IS NULL","from_json(concat('[',j.old_json,']'),'ARRAY<STRING>')[0] IS DISTINCT FROM get_json_object(s.props_json,'$.201')","from_json(concat('[',j.new_json,']'),'ARRAY<STRING>')[0] IS DISTINCT FROM get_json_object(s.new_props,'$.201')"]
assert c.sql('journal-full-values',f"WITH stages AS ({stages}) SELECT count(*),count_if({' OR '.join(checks)}) FROM stages s LEFT JOIN {F}.property_journal VERSION AS OF {jv} j ON s.source_system=j.source_system AND s.rel_type_id=j.type_id AND s.id=j.id AND j.source_feed='fixture-scheduled-fenced' AND s.batch=j.source_position")==[['800000','0']]
for b in s['batches']:
 i=b['batch'];r=c.sql('descriptor-'+str(i),f"SELECT table_versions_json,source_progress_json,schema_revisions_json FROM {F}.manifest_r11 WHERE publication_id='r13-{i}'");assert len(r)==1 and json.loads(r[0][0])==b['versions'] and json.loads(r[0][1])['fixture-scheduled-fenced']=={'epoch':'e','position':i} and json.loads(r[0][2])=={'pilot:'+str(k):'r1' for k in range(5)}
c.sql('final-detail',f'DESCRIBE DETAIL {F}.edge_current');(out/'summary.json').write_text(json.dumps({'state':'passed','untouched_full17':9219981,'journal_exact':800000,'descriptors':4,'scope':'final untouched parity plus every journal value; changed canonical checks at each publication in timed harness'},indent=2));c.history();c.close();print('Scheduled preservation verified')
