#!/private/tmp/ashlar-paths-wheel-command-20261010-a/environment/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from ashlar.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
