import json,hashlib
from pathlib import Path
R=Path('/Users/erik/Projects/ashlar'); child=Path('/private/tmp/astra-paths-reader-review-20261010-c.json');data=json.loads(child.read_text());outdir=Path('/private/tmp/astra-paths-reader-predecessor-20261010-c');outdir.mkdir(exist_ok=False)
def d(p):
 b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
snap=[]
for rel,sha in data['sourcePins'].items():
 p=R/rel;assert d(p)['sha256']==sha;q=outdir/p.name;q.write_bytes(p.read_bytes());snap.append(d(q))
for v in data['files']:
 p=Path(v['path']);assert d(p)==v
report={'reviewer':'/root/astra_plan_review','verdict':'request-narrow-reader-primary-correction','scope':'Paths observation and actual reader/provider cleanup facts. Classification controls pass; aggregate original cancellation preservation on affected reader closing path is withheld.','sourceSnapshots':snap,'childReview':d(child),'finding':{'id':'PATH-READER-PRIMARY-001','priority':'P1','path':'src/ashlar_host/publication_reader.py','location':'open_commerce_reader final transport close','provenance':'Inherited behavior, not introduced by fact instrumentation. Current affected source was independently checked.','evidence':'Exact acquired-region AST control preserves real try/except/finally and injected inert ports. Three postyield KI/SystemExit/GeneratorExit primaries each get replaced by ordinary transport-close OSError; four further ordinary-guard/cleanup combinations also demonstrate replacement.','remedy':'Use the owning primary-preserving finalization policy around the actual close callback after recording the existing primary. Keep independent cleanup facts and exact omission behavior except explicit primary bug correction; test both state-present and omitted cases.','limit':'This inherited concrete counterexample prevents a complete cancellation-preservation claim; source classification pass alone does not establish corrected closure.'},'passed':'38 source/inert tests, four independent workflow cases, state type/read-only/singleclaim controls, actual provider method guard versus rollback/close. Child raw artifact digests verified.','qualificationLimits':['No native, SDK worker, receiver, network or credentials used.','Exact AST acquired-region control is not whole-factory/native execution.','No approval of unmodified predecessor for cancellation guarantees.'],'files':[d(Path(v['path'])) for v in data['files']]}
out=Path('/private/tmp/astra-paths-reader-review-20261010-c-parent.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(d(out)))
