from pathlib import Path
import ast,hashlib,json
R=Path('/private/tmp/ashlar-otel-installed-receiver-probe-20261010-e');prep=Path('/private/tmp/ashlar-otel-installed-preparation-20261010-c')
def d(p):
 b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
assert d(R/'candidate.py')['sha256']=='6c9413bd8dab57fa9447474fd10103cb342e665a4609e92aa7de7a79d6494cad'
assert d(R/'command.json')['sha256']=='3b718c20877ea804ba759a7cd49c3f3537996eb7d147be37cf0f6d03cb713b74'
assert d(prep/'freeze-b.json')['sha256']=='1a2ccfebe9992d87f4c9e28d5c249da1d96a20137443242126b7a5682f0b3ae2'
command=json.loads((R/'command.json').read_text());assert command['argv']==[str(prep/'environment/bin/python'),'-I','-B',str(R/'candidate.py')]
assert command['cwd']==str(R) and command['env']=={'PATH':'/usr/bin:/bin'}
assert command['sourceCommit']=='02136b9e68afe0f0b175186c6444662347fc463a'
new=ast.parse((R/'candidate.py').read_text());old=ast.parse(Path('/private/tmp/ashlar-otel-installed-receiver-probe-20261010-c/candidate.py').read_text())
def owned(t):return {n.name:ast.dump(n,include_attributes=False) for n in t.body if isinstance(n,(ast.FunctionDef,ast.ClassDef))}
a,b=owned(new),owned(old)
for name in ('write','mark','cleanup_failure','Server','Receiver','attributes','scope'):assert a[name]==b[name]
assert not any((R/n).exists() for n in ('result.json','.result-stage.json','capture','receiver-observations.json','cli-output.json','expected.json'))
assert not list(R.glob('request-*.pb'))
report={'reviewer':'/root/astra_plan_review','verdict':'approve-exact-direct-receiver-command-conditional-on-root-custody-and-freshness','scope':'Two synthetic traced lifecycles through current installed public diagnostic_run and installed CLI main retrieval; real bounded loopback HTTP receiver is authorized root execution only. No reviewer receiver/network/worker execution.','source':d(R/'candidate.py'),'command':d(R/'command.json'),'preparationFreeze':d(prep/'freeze-b.json'),'preparationReview':d(Path('/private/tmp/astra-otel-installed-preparation-review-20261010-c.json')),'checks':['Exact selected installed interpreter -I -B, PATH-only environment and explicit working directory; no checkout import path/private facade access.','Both run lifecycles are enclosed by public diagnostic_run. Dependency admission and owned worker closure are actual composition responsibilities. Startup fallback is not independently fault-qualified by this success candidate.','Two attempts yield six logs, two root spans and two cumulative integer counter points in nine endpoint requests (6/2/1). Incoming trace fixtures are absent; contexts derive from actual SDK through public run events.','Oracle compares retained local event bytes to decoded OTLP resource/schema URL/scope/body/typed attrs/time/severity/full log flags/span low8 flags/status/root parentlessness/counter bag and explicit known signal loss.','Installed CLI main uses restored argv/stdout and exact public reader serialization equality. This is installed CLI callable behavior, not a separate console executable process.','All previously approved seven helper/class ASTs are unchanged from actual-C reviewed candidate, including bounded receiver body/count, accepted-socket timeout, primary cleanup, raw pre-oracle retention and staged closed no-clobber final availability.','Candidate fresh outputs absent at review; command requires root immediate recheck and closing selected resource custody.'],'bounds':command['bounds'],'findings':[],'conditions':['Root immediately verifies complete selected installed/preparation/interpreter/candidate vector and fresh result/stage/capture/raw output paths.','Root executes exact direct foreground command, preserves actual stdout/stderr and all-outcome closing verification; no outer forced-termination wrapper.','Review actual raw requests/capture/outcomes independently before evidence landing or support assertion.'],'limits':['No spanless/explicit parent/retry selection exercised through composition; earlier distinct API qualification remains separately scoped.','No actual business/native/ACK/credential operation; operation names identify controlled synthetic attempts.','No outage/concurrency/fault pilot or full C006 assurance. Direct foreground scope carries no abrupt-root-death/global deadline/process census guarantee.']}
p=Path('/private/tmp/astra-otel-installed-receiver-command-review-20261010-e.json');p.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(d(p)))
